import { MerchantConfig } from '../types/merchant';

export const MOCK_MERCHANTS: Record<string, MerchantConfig> = {
  'merchant-fabet': {
    id: 'FABET',
    name: 'Fabet Fajas',
    logo: new URL('../../assets/imgs/FABET-LOGO.jpg', import.meta.url).href,
    badgeText: 'Tienda Verificada',
    primaryColor: '#e93a3a', // Indigo
    secondaryColor: '#e95555',
    theme: {
      primary: '#e93a3a',
      primaryHover: '#e93a3a',
      primaryLight: '#eef2ff',
      primaryForeground: '#ffffff',
    },
    phoneCountryCode: '+51',
    phonePlaceholder: '9XXXXXXXX',
    cutoffTime: '18:00',
    cutoffEnabled: true,
    cutoffNoticeTitle: 'Hora de corte: 10:00 p.m',
    cutoffNoticeMessage: 'Asegura tu envío registrando tus datos antes de la hora de corte para despacho lo más pronto posible.',
    cutoffPassedMessage: 'Has ingresado después de las 18:00. Tu envío se programará con prioridad para primera hora del día hábil siguiente.',
    whatsappEnabled: true,
    whatsappNumber: '+51924834528',
    formTitle: 'Formulario de Envío',
    formSubtitle: 'Ingresa los datos del destinatario para coordinar y despachar tu pedido.',
    successTitle: '¡Registro Exitoso!',
    successMessage: 'Tu envío ha sido programado correctamente. Verifica los datos y envíalos por chat con el botón verde.',
    allowedCouriers: ['Shalom', 'Olva Courier', /*'Marvisur', 'Delivery(Solo Lima)'*/],
    defaultCourier: 'Shalom',
    supportPhone: '+51924834528',
    supportEmail: 'contacto.fabet@gmail.com',
    fields: [
      {
        id: 'phone',
        type: 'phone',
        label: 'Tu WhatsApp',
        placeholder: '9XXXXXXXX',
        required: true,
        helpText: 'Te contactaremos por este número para enviarte tu clave de recojo y boleta.',
        section: 'personal',
      },
      {
        id: 'fullName',
        type: 'text',
        label: 'Nombre completo del destinatario',
        placeholder: 'Ej: Ayrton Rodriguez...',
        required: true,
        section: 'personal',
      },
      {
        id: 'documentNumber',
        type: 'text',
        label: 'DNI / Documento de Identidad',
        placeholder: '8 dígitos para DNI o CE',
        required: true,
        helpText: 'Requerido por la agencia courier para entregar el paquete.',
        section: 'personal',
      },
      {
        id: 'deliveryType',
        type: 'select',
        label: 'Modalidad de Entrega',
        required: true,
        defaultValue: 'agencia',
        options: [
          { value: 'agencia', label: '🏢 Retiro en Agencia (Shalom / Olva)' },
          { value: 'domicilio', label: '🏠 Envío a Domicilio' },
        ],
        section: 'delivery',
      },
      {
        id: 'courier',
        type: 'select',
        label: 'Courier o Empresa de Transporte',
        required: true,
        defaultValue: 'Shalom',
        options: [
          { value: 'Shalom', label: 'Shalom (Recomendado - Rápido y económico)' },
          { value: 'Olva Courier', label: 'Olva Courier' },
          // { value: 'Marvisur', label: 'Marvisur carga pesada' },
          // { value: 'Motorizado', label: 'Motorizado Express (Solo Lima)' },
        ],
        section: 'delivery',
      },
      {
        id: 'department',
        type: 'select',
        label: 'Departamento / Provincia / Distrito',
        placeholder: 'Ej: Lima / Lima / Comas',
        required: true,
        section: 'delivery',
      },
      {
        id: 'destinationSede',
        type: 'select',
        label: 'Sede de Agencia o Dirección de Entrega',
        placeholder: 'Ej: Agencia Shalom Año Nuevo / Av. Tupac Amaru N° 7837',
        required: true,
        options: [
          { value: 'Shalom', label: 'Shalom Empresarial' },
          { value: 'Olva Courier', label: 'Olva Courier Puerta a Puerta' },
        ],
        section: 'delivery',
      },
      {
        id: 'reference',
        type: 'text',
        label: 'Referencia adicional',
        placeholder: 'Ej: A una cuadra de la entrada de Collique, frente a farmacia',
        required: false,
        section: 'delivery',
      },
      {
        id: 'notes',
        type: 'textarea',
        label: 'Notas del pedido o instrucciones especiales',
        placeholder: 'Ej: Deseo guía de talla, color beige, 2 unidades de faja, etc.',
        required: false,
        rows: 2,
        section: 'additional',
      },
    ],
  },

  'merchant-mayul': {
    id: 'merchant-test',
    name: 'Mayul',
    logo: new URL('../../assets/imgs/MAYUL-LOGO.jpg', import.meta.url).href,
    badgeText: 'Distribuidor Oficial',
    primaryColor: '#e70078', // Sky Blue
    secondaryColor: '#ff378e',
    theme: {
      primary: '#e70078',
      primaryHover: '#ff378e',
      primaryLight: '#f0f9ff',
      primaryForeground: '#ffffff',
    },
    phoneCountryCode: '+51',
    phonePlaceholder: '9XXXXXXXX',
    cutoffTime: '16:30',
    cutoffEnabled: true,
    cutoffNoticeTitle: 'Hora de corte: 10:00 p.m',
    cutoffNoticeMessage: 'Si ya completastes tus datos correctamente, hablemos de tu talla por Whatsapp.',
    whatsappEnabled: true,
    whatsappNumber: '+51987061014',
    formTitle: 'Registro de datos para Envios',
    formSubtitle: 'Ingresa tus datos exactos para el rotulado.',
    successTitle: '¡Orden de Despacho Generada!',
    successMessage: 'Tus datos fueron cargados. Envía tu confirmación para emitir tu guía de remisión.',
    allowedCouriers: ['Shalom', /*'Marvisur',*/ 'Olva Courier'],
    defaultCourier: 'Shalom',
    supportPhone: '+51987061014',
    fields: [
      {
        id: 'phone',
        type: 'phone',
        label: 'Tu WhatsApp *',
        placeholder: '9XXXXXXXX',
        required: true,
        helpText: 'Recibirás el código de tracking y fotos de la Boleta.',
        section: 'personal',
      },
      {
        id: 'fullName',
        type: 'text',
        label: 'Nombre completo',
        placeholder: 'Ej: Carlos Alberto Sánchez Rivas',
        required: true,
        section: 'personal',
      },
      {
        id: 'documentNumber',
        type: 'text',
        label: 'DNI / CE',
        placeholder: 'Número de documento',
        required: true,
        section: 'personal',
      },
      {
        id: 'email',
        type: 'email',
        label: 'Correo Electrónico (Para factura / boleta)',
        placeholder: 'cliente@ejemplo.com',
        required: false,
        section: 'personal',
      },
      {
        id: 'courier',
        type: 'select',
        label: 'Agencia Courier',
        required: true,
        defaultValue: 'Shalom',
        options: [
          { value: 'Shalom', label: 'Shalom Empresarial' },
          { value: 'Olva Courier', label: 'Olva Courier Puerta a Puerta' },
        ],
        section: 'delivery',
      },
      {
        id: 'destinationAddress',
        type: 'text',
        label: 'Ciudad y Dirección de Destino',
        placeholder: 'Ej: Arequipa - Agencia Shalom Parra',
        required: true,
        section: 'delivery',
      },
      {
        id: 'notes',
        type: 'textarea',
        label: 'Indicaciones sobre el paquete',
        placeholder: 'Ej: Manejar con cuidado (Pantalla/Vidrio templado)',
        required: false,
        rows: 2,
        section: 'additional',
      },
    ],
  },

  'merchant-talu': {
    id: 'merchant-logistica',
    name: 'Tienda Talú',
    logo: new URL('../../assets/imgs/TALU-LOGO.jpg', import.meta.url).href,
    badgeText: 'Tienda de Fajas',
    primaryColor: '#6a38aa', // Emerald
    secondaryColor: '#8546f8',
    theme: {
      primary: '#6a38aa',
      primaryHover: '#8546f8',
      primaryLight: '#ecfdf5',
      primaryForeground: '#ffffff',
    },
    phoneCountryCode: '+51',
    phonePlaceholder: '9XXXXXXXX',
    cutoffTime: '19:00',
    cutoffEnabled: false, // Informs cutoff time but doesn't hard-block
    cutoffNoticeTitle: 'Hora de corte de taller: 19:00',
    cutoffNoticeMessage: 'Asegura tu envío registrando tus datos antes de la hora de corte para despacho lo más pronto posible.',
    whatsappEnabled: true,
    whatsappNumber: '+51910205066',
    formTitle: 'Formulario de Envío',
    formSubtitle: 'Completa los datos de la persona que recogerá en agencia.',
    successTitle: '¡Datos de Carga Registrados!',
    successMessage: 'Haz clic en el botón de WhatsApp para enviar el formato de rotulado al whatsapp.',
    allowedCouriers: ['Shalom', 'Olva Courier'],
    defaultCourier: 'Shalom',
    supportPhone: '+51910205066',
    fields: [
      {
        id: 'phone',
        type: 'phone',
        label: 'Tu WhatsApp',
        placeholder: '9XXXXXXXX',
        required: true,
        section: 'personal',
      },
      {
        id: 'fullName',
        type: 'text',
        label: 'Nombre completo de quien recoge',
        placeholder: 'Nombres y Apellidos exactos según DNI',
        required: true,
        section: 'personal',
      },
      {
        id: 'documentNumber',
        type: 'text',
        label: 'Número de DNI',
        placeholder: '8 dígitos',
        required: true,
        section: 'personal',
      },
      {
        id: 'courier',
        type: 'select',
        label: 'Empresa de Transporte / Courier',
        required: true,
        defaultValue: 'Shalom',
        options: [
          { value: 'Shalom', label: 'Shalom' },
          { value: 'Olva Courier', label: 'Olva Courier' },
        ],
        section: 'delivery',
      },
      {
        id: 'destinationAddress',
        type: 'text',
        label: 'Ciudad y Agencia Destino',
        placeholder: 'Ej: Huancayo - Terminal El Tambo',
        required: true,
        section: 'delivery',
      },
      {
        id: 'notes',
        type: 'textarea',
        label: 'Detalles de paquetes o mercadería',
        placeholder: 'Ej: Deseo guía de talla, color beige, 2 unidades de faja, etc.',
        required: false,
        rows: 2,
        section: 'additional',
      },
    ],
  },
/*
  'zapateria-express': {
    id: 'zapateria-express',
    name: 'Zapatería Express Perú',
    badgeText: 'Calzado & Moda',
    logo: 'https://tu-dominio.com/logo.png', // Opcional
    primaryColor: '#e11d48', // Color principal (Hex)
    secondaryColor: '#be123c',
    phoneCountryCode: '+51',
    phonePlaceholder: '9XXXXXXXX',
    cutoffTime: '17:30', // Hora de corte (HH:mm)
    cutoffEnabled: true,
    whatsappEnabled: true,
    whatsappNumber: '+51987111222', // WhatsApp de la tienda que recibe el pedido
    formTitle: 'Registro de Envíos de Calzado',
    formSubtitle: 'Completa tus datos para enviarte el calzado a tu ciudad hoy mismo.',
    allowedCouriers: ['Shalom', 'Olva Courier'],
    defaultCourier: 'Shalom',
    fields: [
      {
        id: 'phone',
        type: 'phone',
        label: 'Tu WhatsApp',
        required: true,
        placeholder: '9XXXXXXXX',
      },
      {
        id: 'fullName',
        type: 'text',
        label: 'Nombre completo',
        required: true,
      },
      {
        id: 'documentNumber',
        type: 'text',
        label: 'DNI para recojo en agencia',
        required: true,
      },
      {
        id: 'destinationAddress',
        type: 'text',
        label: 'Agencia o Ciudad de destino',
        required: true,
      },
    ],
  },
*/
};

// Map the URL reference merchant id directly to merchant-demo
MOCK_MERCHANTS['u_9c98qwpvm'] = {
  ...MOCK_MERCHANTS['Fabet EIRL'],
  id: 'u_9c98qwpvm',
  name: 'Fabet Fajas',
  badgeText: 'Tienda Online',
  formTitle: 'Formulario de Envío',
  formSubtitle: 'Ingresa los datos para agendar tu pedido.',
};

/**
 * Returns list of all available mock merchant keys
 */
export function getAvailableMerchantIds(): string[] {
  return Object.keys(MOCK_MERCHANTS);
}
